---
format: 
    html:
      toc: true
      toc-location: left
      page-layout: full
css: ./web.css
---

:::{.hero-banner}
# Welcome to the HPC-Pipes workshop 
:::

#### <span style="color: red;">PLEASE READ BEFORE COURSE!</span>

## Course requirements 

:::{.callout-warning title="Required preparation"}
You are expected to complete the required setup, including tool installation (Docker) and account creation (UCloud). 

- [Docker](https://www.docker.com/products/docker-desktop/) - click on `Download Docker Desktop`.

**Note for Windows users:** Installing Docker Desktop requires administrative privileges on your computer. You will be prompted to enter your KU username and password during the installation process. Additionally, Docker Desktop depends on the Windows Subsystem for Linux (WSL), which will also need to be installed.

As for other software, we will provide access to a Danish HPC platform, UCloud, with all necessary software pre-installed. **Please read [Using UCloud for exercises](#using-ucloud-for-exercises) carefully**. 

**If you prefer to run the exercises on your personal laptop or a different server, please ensure you have the following software installed:**

- [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) - miniconda or miniforge recommended. 
- [snakemake](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html) use conda for this!
- [nextflow](https://www.nextflow.io/docs/latest/install.html)
- [Apptainer](https://apptainer.org/docs/admin/latest/installation.html), formerly known as [Singularity](https://docs.sylabs.io/guides/3.0/user-guide/installation.html#).  

:::

### Using UCloud for exercises 

:::{.callout-warning}
Follow the instructions below if you have an account at a Danish university. You will need your institutional email to proceed. Unfortunately, this will not work for those without a university email.
:::

1. Create an account on [UCloud](https://cloud.sdu.dk/) with your institution's credentials 
2. Use the link below to join our workspace where you will find a setup environment^[*link activated a week before the workshop*.]

<p align="center">
  <a href="https://cloud.sdu.dk/app/projects/invite/77dabc7d-2077-48ef-a046-f396ca6a32ef">
    <button class="btn">Invite link to UCloud workspace</button>
  </a>
</p>

3. You’re all set! You will receive instructions on how to navigate through UCloud during the course.

### Reading material (optional)

- [The Turing way](https://the-turing-way.netlify.app/reproducible-research/reproducible-research). It offers comprehensive guidance on reproducible research practices, including setting up computational environments and managing reproducible workflows. 
- Mölder, Felix, et al. "Sustainable data analysis with Snakemake." F1000Research 10 (2021). [Link to article](https://f1000research.com/articles/10-33/v2). Best practices using Snakemake to develop your pipelines. 
- Check our content on HPC pipes. 

## Agenda

### Day 1 
| Time | Activity | Time | Activity |
|:-|:----|:-|:----|
| *8:45*	|	*Morning coffee (optional)* |  
| 9:00	|	Intro to HPC & onboarding | 13:00	|	Software mgmt III (docker) |
| 9:45	|	Software mgmt I (conda) | 13:45	|	Computations mgmt I (smk) |
| 10:30	|	*Coffee break* |  14:15	|	*Coffee break* |
| 10:45	|	Software mgmt II (conda) | 14:30	|	Computations mgmt I (smk) |
| 12:00	|	*Lunch break* | 15:30	|	Wrap-up |

::: {.hero-buttons}
[Environments exercises](./pipes-ex-envs.qmd){.btn-action .btn .btn-success .btn-lg role="button"}
[Snakemake I exercises](./pipes-ex-smk.qmd){.btn-action-smk .btn .btn-info .btn-lg role="button"}
::: 

### Day 2

| Time | Activity | Time | Activity |
|:-|:----|:-|:----|
| *8:45*	|	*Morning coffee (optional)* |  
| 9:00	|	Computations mgmt II (smk) | 12:00	|	*Lunch break* |
| 9:45	|	Exercise - smk integration | 13:00	|	Exercise nf + wrap up|
| 10:15	|	*Coffee break* |  14:15	|	*Coffee break* |
| 10:30	|	Exercise - smk implementation | 14:30	|	Build your own pipeline |
| 11:15	|	Computations mgmt III (nf) | 15:00	|	Wrap-up |

::: {.hero-buttons}
[Snakemake II exercises](./pipes-ex-smk-self.qmd){.btn-action-smk .btn-action .btn .btn-success .btn-lg role="button"}
[Snakemake III exercises](./pipes-ex-smk-fast.qmd){.btn-action-smk .btn-action .btn .btn-success .btn-lg role="button"}
[Nextflow I exercises](./pipes-ex-nf.qmd){.btn-action-smk .btn-action .btn .btn-success .btn-lg role="button"  style="background-color: #14b393ff !important"}
::: 


### Download the slides

<p align="center">
    <button class="btn" disabled>Download slides</button> 
</p>

<!--  <a href="./hpcpipes-sandbox.zip" download="hpcpipes-sandbox.zip"> -->
<!--  <a -->

## Discussion and feedback

We hope you enjoyed the workshop. As data scientists, we also would be really happy for some quantifiable info and feedback - we want to build things that the Danish health data science community is excited to use. <b>Please, fill up the [feedback form](https://forms.office.com/e/ndK0MtWrwW) before you head out for the day ^[*link activated on the day of the workshop*.].</b>

&nbsp;


:::{.callout-note  appearance="simple" icon=false} 
<h4 align=center>Nice meeting you and we hope to see you again!</h4> 
::: 

#### About the National Sandbox project 

The Health Data Science Sandbox aims to be a **training resource for bioinformaticians, data scientists, and those generally curious about how to investigate large biomedical datasets**. We are an active and developing project **seeking interested users** (both trainees and educators). All of our open-source materials are available on our [Github page](https://github.com/hds-sandbox) and can be used on a computing cluster! We work with both [UCloud](https://cloud/sdu.dk), [GenomeDK](https://genome.au.dk) and [Computerome](https://www.computerome.dk/), the major Danish academic supercomputers.
