---
format: 
  html
css: ./web.css
---

:::{.hero-banner}
# Welcome to the HPC-Launch workshop 
:::

## Agenda

| Time | Activity | Time | Activity |
|:-|:----|:-|:----|
| *8:45*	|	*Morning coffee (optional)* |  
| 9:00	|	Introduction to the Sandbox project | 12:00	|	*Lunch break* |
| 9:15	|	Introduction to HPC: the basics | 13:00	|	Step-by-step: solutions I |
| 10:15	|	*Coffee break* |  14:15	|	*Coffee break* |
| 10:30	|	DK HPC resources, access, and intro to UCloud | 14:30	|	Step-by-step: solutions II |
| 11:15	|	Intro to RDM for health data science | 16:00	|	Discussions & Wrap-up |

## Course requirements 

:::{.callout-warning title="Required preparation"}
You are expected to complete the required setup, including tool installation and account creation. 

- [Git](https://git-scm.com/downloads) for version control of your projects
- A [Zenodo account](https://zenodo.org/) for archiving and sharing your research outputs
- [Python](https://www.python.org/)
- [pip](https://pip.pypa.io/en/stable/installation/) for managing Python packages
- [Cookicutter](https://cookiecutter.readthedocs.io/en/stable/) for creating folder structure templates (`pip install cookiecutter`)
- [md5sum](https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html)
  ```{.bash filename="Terminal"}
  # ---- cookiecutter -----
  pip install cookiecutter

  # ---- md5sum from coreutils package-----
  # On Ubuntu/Debian
  apt-get install coreutils
  # On macOS
  brew install coreutils
  ```
- *Highly recommended*: a [GitHub account](https://github.com/) for hosting and collaborating on projects

Note: If you encounter any issues, we will grant access to a Danish HPC platform where all the necessary software is pre-installed. Please read the next section carefully.
:::

### Using UCloud for exercises 

1. Create an account on [UCloud](https://cloud.sdu.dk/)
2. Use the link below to join our workspace where you will find a setup environment^[*link activated a week before the workshop*.]

&nbsp;

 <p align="center">
  <a href="https://cloud.sdu.dk/app/projects/invite/b8c2ed67-3c40-4ccb-8a52-1f289c7e3df0" style="background-color: #4266A1; color: #FFFFFF; padding: 30px 20px; text-decoration: none; border-radius: 5px;">
    Invite link to
    UCloud workspace
  </a>
</p>

&nbsp;


## Discussion and feedback

We hope you enjoyed the workshop. As data scientists, we also would be really happy for some quantifiable info and feedback - we want to build things that the Danish health data science community is excited to use. <b>Please, fill-up the feedback fork [LINK] before you head out for the day ^[*link activated on day of the workshop*.].</b>

&nbsp;

You can download our RDM roadmap [here](https://hds-sandbox.github.io/RDM_biodata_course/develop/cheatSheet.html). 

:::{.callout-note  appearance="simple" icon=false} 
<h4 align=center>Nice meeting you and we hope to see you again!</h4> 
::: 

### About the National Sandbox project 

The Health Data Science Sandbox aims to be a **training resource for bioinformaticians, data scientists, and those generally curious about how to investigate large biomedical datasets**. We are an active and developing project **seeking interested users** (both trainees and educators). All of our open-source materials are available on our [Github page](https://github.com/hds-sandbox) and can be used on a computing cluster! We work with both [UCloud](https://cloud/sdu.dk), [GenomeDK](https://genome.au.dk) and [Computerome](https://www.computerome.dk/), the major Danish academic supercomputers.